
def create_empty_table():

    info_dict = {'crash': [],
                 'car': [],
                 'clear': [],
                 'cloudy': [],
                 'raining': [],
                 'snowing': [],
                 'fog/visibility': [],
                 'other weather': [],
                 'wind': [],
                 'daylight': [],
                 'dusk-dawn': [],
                 'dark-street lights': [],
                 'dark-no street lights': [],
                 'dark-street lights not functioning': [],
                 'dry': [],
                 'wet': [],
                 'snowy-icy': [],
                 'slippery (muddy, oily, etc.)': [],
                 'holes, deep rut': [],
                 'loose material on roadway': [],
                 'obstruction on roadway': [],
                 'construction - repair zone': [],
                 'reduced roadway width': [],
                 'flooded': [],
                 'other condition': [],
                 'no unusual conditions': [],
                 'stopped': [],
                 'proceeding straight': [],
                 'ran off road': [],
                 'making right turn': [],
                 'making left turn': [],
                 'making u turn': [],
                 'backing': [],
                 'slowing/stopping': [],
                 'passing other vehicle': [],
                 'changing lanes': [],
                 'parking manuever': [],
                 'entering traffic': [],
                 'other unsafe turning': [],
                 'xing into opposing lane': [],
                 'parked': [],
                 'merging': [],
                 'traveling wrong way': [],
                 'other movement': [],
                 'head-on': [],
                 'side swipe': [],
                 'rear end': [],
                 'broadside': [],
                 'hit object': [],
                 'overturned': [],
                 'vehicle/pedestrian': [],
                 'other type of collision': []}

    return info_dict